name: Auto-Revert
on:
  # Trigger the workflow on code merge to CI branches.
  push:
    branches: [ master ]

jobs:

  Build:

    runs-on: ubuntu-latest

    steps:
          
      - name: Build
        run: |
          ls -la
          exit 1
          
  Revert:

    runs-on: ubuntu-latest

    needs: Build

    if: failure()

    steps:
    
    # Update the path to ensure that we're using the correct git
      - name: Update PATH
        run: |
          echo "/usr/bin" >> $GITHUB_PATH
          echo $GITHUB_PATH
    
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Multiproduct
        uses: actions/checkout@v2
        with:
          # Fetch depth of 0 forces it to get the whole history, including the .git folder - the default will not have the .git folder
          # https://github.com/actions/checkout/issues/335
          fetch-depth: 0
    
    
      - name: ls -alrth
        run: |
          ls -alrth
          
      - name: Git Log
        run: |
          /usr/bin/git log -3
      
      - name: Git Configs
        run: |
          /usr/bin/git config --global user.name "tester"
          /usr/bin/git config --global user.email "not-tester@linkedin.com"

#       - name: Git Revert
#         run: |
#           git revert -m 1 
      
#       - name: Git Commit
#         run: |
#           /usr/bin/git commit -am "Revert commit ${GITHUB_SHA} \n AUTO_MERGE_ENABLED"
#           ls
          
#       - name: Git Push
#         run: |
#           /usr/bin/git push --verbose


      - name: Revert
        run: |
#           git checkout -b tester/autorevert_${GITHUB_SHA}
          git revert -m 1 ${GITHUB_SHA} --no-commit
          git commit -m "Revert commit ${GITHUB_SHA} \n AUTO_MERGE_ENABLED"
#          git push origin tester/autorevert_${GITHUB_SHA}
          git push


      - name: Git Log
        run: |
          /usr/bin/git log -3
